# Generated by Django 4.2.2 on 2023-07-02 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import authuser.models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(default=authuser.models.generate_api_key, max_length=200)),
                ("expires", models.DateTimeField(default=authuser.models.expiry_time)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
