# Generated by Django 4.2.2 on 2023-07-02 02:53

from django.db import migrations, models

import authuser.models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0002_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(default=authuser.models.generate_api_key, max_length=200, unique=True),
        ),
    ]
