# Generated by Django 4.2.2 on 2023-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authuser", "0003_alter_apikey_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
