# Generated by Django 4.2.2 on 2023-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0003_usersettings_feedbin_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="hn_username",
            field=models.CharField(blank=True, help_text="Your Hacker News username", max_length=40),
        ),
    ]
