# Generated by Django 4.2.6 on 2023-10-21 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0005_linkscreenshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkscreenshot",
            options={"ordering": ["-added"]},
        ),
    ]
